# Generated by Django 3.1 on 2020-08-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrijednost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proizvodjac', models.CharField(max_length=100)),
                ('Model', models.CharField(max_length=100)),
                ('Godiste', models.IntegerField(default=0)),
                ('Kilometara', models.IntegerField(default=0)),
                ('Gorivo', models.CharField(max_length=20)),
                ('Kubika', models.FloatField(default=0)),
                ('BrojVrata', models.CharField(max_length=5)),
                ('Cijena', models.IntegerField(default=0)),
                ('Kilovata', models.IntegerField(default=0)),
                ('Tip', models.CharField(max_length=30)),
                ('Pogon', models.CharField(max_length=20)),
                ('Mjenjac', models.CharField(max_length=20)),
                ('Emisija', models.CharField(max_length=10)),
                ('Datum', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
